image: $DOCKER_REGISTRY_PREFIX/2smart/utils/combined-ci-image:25-dind

stages:
  - test
  - build
  - buildx

services:
  - name: $DOCKER_REGISTRY_PREFIX/2smart/base-images/docker-dind:25-dind
    alias: docker

before_script:
  - git clone https://oauth2:$ACCESS_TOKEN@$DOCKER_UTILS_REPO_URL
  - mv docker-utils/utils.sh docker.sh

lint:
  stage: test
  script:
    - npm ci
    - npm run lint
  only:
    - 'merge_requests'
    - 'master'

test:
  stage: test
  script:
    - npm ci
    - npm run test
  only:
    - 'merge_requests'
    - 'master'

build:
  stage: build
  script:
    - ./docker.sh rundaemon
    - ./docker.sh build
    - ./docker.sh push
  only:
    - 'master'

buildx:
  stage: buildx
  script:
    - ./docker.sh rundaemon
    - ./docker.sh login
    - SOURCE_TAG=$MULTIPLATFORM_TAG ./docker.sh buildx
  when: manual
  allow_failure: true